# This formula is regenerated by the ankra-cli release workflow from
# packaging/homebrew/ankra.rb.tmpl in ankraio/ankra-cli. Manual edits here
# will be overwritten on the next release; change the template instead.
#
# There is deliberately no `version` stanza: `brew audit` fails a tap whose
# declared version it can already scan from the stable URL (redundant_version),
# and every release URL below carries the tag. That is why the URLs interpolate
# nothing - the release workflow substitutes the version into them directly.
class Ankra < Formula
  desc "Command-line interface for the Ankra Kubernetes platform"
  homepage "https://ankra.io"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/ankraio/ankra-cli/releases/download/v0.23.0/ankra-cli-darwin-arm64"
      sha256 "6649ebb88c6d7db885a8b0ddfceedc0d510bfec13f5799f9896cc9402cc559bb"
    end
    on_intel do
      url "https://github.com/ankraio/ankra-cli/releases/download/v0.23.0/ankra-cli-darwin-amd64"
      sha256 "f67ac7fa87f47c12739085715e4368ba655977a9f6cc5f5749bffcc6d30ff364"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ankraio/ankra-cli/releases/download/v0.23.0/ankra-cli-linux-arm64"
      sha256 "a7d32584949d6eb5822442d05e10690ea359f205d0350a2d21433bfc00d3ad93"
    end
    on_intel do
      url "https://github.com/ankraio/ankra-cli/releases/download/v0.23.0/ankra-cli-linux-amd64"
      sha256 "11596b613511d0eebd952119b3ccf451fa44b148babfa7ef52c8bd57a7489cb3"
    end
  end

  def install
    # Release assets are bare binaries (no archive), so the download has no
    # execute bit; set it before generating completions runs the binary.
    bin.install Dir["ankra-cli-*"].first => "ankra"
    chmod 0755, bin/"ankra"
    generate_completions_from_executable(bin/"ankra", "completion")
  end

  test do
    assert_match "ankra version v#{version}", shell_output("#{bin}/ankra --version")
  end
end
