# This formula is regenerated by the ankra-cli release workflow from
# packaging/homebrew/ankra.rb.tmpl in ankraio/ankra-cli. Manual edits here
# will be overwritten on the next release; change the template instead.
#
# There is deliberately no `version` stanza: `brew audit` fails a tap whose
# declared version it can already scan from the stable URL (redundant_version),
# and every release URL below carries the tag. That is why the URLs interpolate
# nothing - the release workflow substitutes the version into them directly.
class Ankra < Formula
  desc "Command-line interface for the Ankra Kubernetes platform"
  homepage "https://ankra.io"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/ankraio/ankra-cli/releases/download/v0.15.0/ankra-cli-darwin-arm64"
      sha256 "6f6d3b8adf6aa9ecb27ad7c8f51cef16df05fcf9bc38190822f52f9a8ed938e0"
    end
    on_intel do
      url "https://github.com/ankraio/ankra-cli/releases/download/v0.15.0/ankra-cli-darwin-amd64"
      sha256 "449a7117f85bbfedd84dd849fcf37cc54f1d1688c31d102446f21c022da73a51"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ankraio/ankra-cli/releases/download/v0.15.0/ankra-cli-linux-arm64"
      sha256 "4d302c225026f59e08393774c3b4675424fcdff7adddf5e973542455299b762a"
    end
    on_intel do
      url "https://github.com/ankraio/ankra-cli/releases/download/v0.15.0/ankra-cli-linux-amd64"
      sha256 "e2f54b9af1d3f7d07172481ae42a83e901f82ac5d460be56f0818752d581a930"
    end
  end

  def install
    # Release assets are bare binaries (no archive), so the download has no
    # execute bit; set it before generating completions runs the binary.
    bin.install Dir["ankra-cli-*"].first => "ankra"
    chmod 0755, bin/"ankra"
    generate_completions_from_executable(bin/"ankra", "completion")
  end

  test do
    assert_match "ankra version v#{version}", shell_output("#{bin}/ankra --version")
  end
end
