# This formula is regenerated by the ankra-cli release workflow from
# packaging/homebrew/ankra.rb.tmpl in ankraio/ankra-cli. Manual edits here
# will be overwritten on the next release; change the template instead.
class Ankra < Formula
  desc "Command-line interface for the Ankra Kubernetes platform"
  homepage "https://ankra.io"
  version "0.9.1"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/ankraio/ankra-cli/releases/download/v#{version}/ankra-cli-darwin-arm64"
      sha256 "1255b3485e20adf54d08b7cbea2e67d71bdfe6521cd1b001fe7002d3f64a6f5f"
    end
    on_intel do
      url "https://github.com/ankraio/ankra-cli/releases/download/v#{version}/ankra-cli-darwin-amd64"
      sha256 "129c555867bfd47d57e22e559484a429af82efcfccc9bf76a6c52af1f5351fb9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ankraio/ankra-cli/releases/download/v#{version}/ankra-cli-linux-arm64"
      sha256 "0b74feb7cfbbe200ae0ed1705dc6a925c7727de76f4bc8ec4afe11348edde874"
    end
    on_intel do
      url "https://github.com/ankraio/ankra-cli/releases/download/v#{version}/ankra-cli-linux-amd64"
      sha256 "8105c947f808a55d5289587128ac33eeece1211c6fd26fe1913381bb83f8a26e"
    end
  end

  def install
    # Release assets are bare binaries (no archive), so the download has no
    # execute bit; set it before generating completions runs the binary.
    bin.install Dir["ankra-cli-*"].first => "ankra"
    chmod 0755, bin/"ankra"
    generate_completions_from_executable(bin/"ankra", "completion")
  end

  test do
    assert_match "ankra version v#{version}", shell_output("#{bin}/ankra --version")
  end
end
